# CUDA_VISIBLE_DEVICES=0 python main.py --object --config configs/objects/sample1.yaml
optimizationParams:
  iterations: 1500
  position_lr_init: 0.0008
  position_lr_final: 0.000016
  feature_lr: 0.020
  feature_lr_final: 0.0030
  scaling_lr: 0.005
  scaling_lr_final: 0.001
  rotation_lr: 0.001
  rotation_lr_final: 0.0002

  densify_grad_threshold: 0.00075

  densify_from_iter: 100
  densify_until_iter: 1400
  densification_interval: 100
  opacity_reset_interval: 600
  style_prompt: '4k, 8k, best quality, ultra-detailed, finely detail, highres, high resolution'

reconOptimizationParams:
  iterations: 40
  position_lr_init: 0.0008
  position_lr_final: 0.000008
  feature_lr: 0.005
  feature_lr_final: 0.004
  opacity_lr: 0.05
  scaling_lr: 0.005
  scaling_lr_final: 0.002
  rotation_lr: 0.001
  rotation_lr_final: 0.0002

  percent_dense: 0.01
  densify_grad_threshold: 0.001

  densify_from_iter: 0
  densify_until_iter: 50
  opacity_reset_interval: 3000
  as_latent_ratio: 0.0

generateCamParams:
  phi_range: [-180, 180]
  max_phi_range: [-180, 180]
  rand_cam_gamma: 1.

  theta_range: [45, 105]
  max_theta_range: [45, 105]

  radius_range: [5.2, 5.5] 
  max_radius_range: [3.5, 5.0]
  default_radius: 3.5
 
  default_fovy: 0.55
  fovy_range: [0.32, 0.60]
  max_fovy_range: [0.16, 0.60]

guidanceParams:
  model_key: 'stabilityai/stable-diffusion-2-1-base'
  perpneg: false
  C_batch_size: 4
  lambda_guidance: 0.1
  noise_seed: 0

  delta_t: 50
  guidance: 'MTSD'
  g_device: 'cuda:1'

  random_delta: True
  vis_interval: 100

visualize_samples: True

modelParams:
  bg_aug_ratio: 0.66

seed: 0

log:
  exp_name: 'objects_generation'
  eval_only: False

objectParams:
  id: 'icecream'
  sh_degree: 3
  text: 'a DSLR photo of an ice cream sundae'
  negative_text: 'oversaturated color, ugly, tiling, low quality, noisy, blurry, out of focus, low contrast, dull, low-resolution, oversaturation.'
  image: ''
  init_guided: 'pointe' # pointe | pointe_330k | pointe_825k
  init_prompt: 'An icecream sundae.'

  # init_guided: 'load'
  # init_prompt: 'path/to/ply/of/gaussians'

  cam_pose_method: 'object'
  use_pointe_rgb: false
  num_pts: 20000
  radius: 0.5


mode_args:
  prune_decay: 0.8 # for compression
  v_pow: 0.1 # for compression
  prune_percent: 0.5 # for compression
